# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMYOdFexYKj1Fjfj2xVIweY2EZBK6rk2
"""

import pandas as pd
baza={
    "FISH":["Durbek Aminovich","Qadamova Zulayho","Arraboyev A","Jo'rayeva G","Xonto'rayev S"],
    "Fan nomi":["Suniy intellekt asoslari","Kompyuter tashkil etish","Kiberhavsizlik asosalri","Elektronika va sxemalar","Kompyuterni tashkil etish",],
    "Mashgulot turi":["maruza","amaliy","amaliy","maruza","maruza"],
    "kafedrasi":["Kompyuter injenering","Suniy intellekt","Axborot texnologiyalri","Axborot texnologiyalari","Axborot tehnologiyalari"]

}
db=pd.DataFrame(baza)
print(db)

excel=pd.ExcelWriter("baza.xlsx")
db.to_excel(excel,index=False)